// Importing necessary modules and components
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google"; //importa as fontes do google
import "./globals.css";     //arquivo de estilos globais
import { ThemeProvider } from '@/context/themeContext'; // Import the ThemeProvider from the context
import Header from "@/components/header/header"; // Import the Header 
import HeaderWrapper from "@/components/header/headerWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Fundação CSN",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider>
          <Header />
          {/* Wrap children with HeaderWrapper */}
            <HeaderWrapper>
              <div className="pt-[10vh]">
                {children}
              </div>
            </HeaderWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
